#!/bin/sh

mkdir -p /var/run/


echo 'openldap:x:1000:1000::/home/openldap:' >>/etc/passwd
echo 'openldap:!:16702:0:99999:7:::' >>/etc/shadow
echo 'openldap:x:1000:' >>/etc/group

opkg update
opkg install openldap-server openldap-utils


# remove unnecessary files after install
rm /tmp/opkg-lists/*

